"""change wallet and project name to wallet_name and project_name

Revision ID: 1c2f5456e978
Revises: f196ce399db9
Create Date: 2026-05-31 01:22:12.444366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c2f5456e978'
down_revision: Union[str, Sequence[str], None] = 'f196ce399db9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('project_name', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.create_index(op.f('ix_projects_project_name'), 'projects', ['project_name'], unique=True)
    op.drop_column('projects', 'name')
    op.add_column('wallets', sa.Column('wallet_name', sa.String(length=100), nullable=False))
    op.drop_index(op.f('ix_wallets_name'), table_name='wallets')
    op.create_index(op.f('ix_wallets_wallet_name'), 'wallets', ['wallet_name'], unique=True)
    op.drop_column('wallets', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_wallets_wallet_name'), table_name='wallets')
    op.create_index(op.f('ix_wallets_name'), 'wallets', ['name'], unique=True)
    op.drop_column('wallets', 'wallet_name')
    op.add_column('projects', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_projects_project_name'), table_name='projects')
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.drop_column('projects', 'project_name')
    # ### end Alembic commands ###
