"""3-3 change projects.id to string

Revision ID: d5fd5eefc02f
Revises: ad6a05f08d74
Create Date: 2026-05-29 20:18:38.704034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5fd5eefc02f'
down_revision: Union[str, Sequence[str], None] = 'ad6a05f08d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('wallet_id', sa.String(), nullable=False))
    op.alter_column('projects', 'id',
               existing_type=sa.UUID(),
               type_=sa.String(),
               existing_nullable=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_foreign_key(None, 'projects', 'wallets', ['wallet_id'], ['id'])
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'id',
               existing_type=sa.String(),
               type_=sa.UUID(),
               existing_nullable=False)
    op.drop_column('projects', 'wallet_id')
    # ### end Alembic commands ###
