"""3-1 drop wallets

Revision ID: d69c21ea355f
Revises: d607ce1d3443
Create Date: 2026-05-29 19:58:18.198780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd69c21ea355f'
down_revision: Union[str, Sequence[str], None] = 'd607ce1d3443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallets_name'), table_name='wallets')
    op.drop_table('wallets')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wallets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('wallet_type', postgresql.ENUM('system', 'project', name='wallet_type'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('created_by', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('wallets_created_by_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('wallets_project_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('wallets_pkey'))
    )
    op.create_index(op.f('ix_wallets_name'), 'wallets', ['name'], unique=True)
    # ### end Alembic commands ###
