"""add bills and wallet transactions

Revision ID: e5eaf123dec7
Revises: 9919ec477044
Create Date: 2026-06-12 20:27:14.677309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5eaf123dec7'
down_revision: Union[str, Sequence[str], None] = '9919ec477044'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bill_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('task_id', sa.UUID(), nullable=False),
    sa.Column('submittedBy', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'cancelled', name='bill_status'), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submittedBy'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bills_approved_by'), 'bills', ['approved_by'], unique=False)
    op.create_index(op.f('ix_bills_id'), 'bills', ['id'], unique=True)
    op.create_index(op.f('ix_bills_submittedBy'), 'bills', ['submittedBy'], unique=False)
    op.create_index(op.f('ix_bills_task_id'), 'bills', ['task_id'], unique=False)
    op.create_table('wallet_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tx_name', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(), nullable=False),
    sa.Column('tx_type', sa.Enum('deposit', 'allocation', 'bill_payment', 'refund', 'cancellation', 'pending', name='tx_type'), nullable=False),
    sa.Column('from_wallet_id', sa.UUID(), nullable=True),
    sa.Column('to_wallet_id', sa.UUID(), nullable=True),
    sa.Column('bill_id', sa.UUID(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=False),
    sa.Column('refund_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], ),
    sa.ForeignKeyConstraint(['from_wallet_id'], ['wallets.id'], ),
    sa.ForeignKeyConstraint(['refund_id'], ['wallet_transactions.id'], ),
    sa.ForeignKeyConstraint(['to_wallet_id'], ['wallets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wallet_transactions_bill_id'), 'wallet_transactions', ['bill_id'], unique=False)
    op.create_index(op.f('ix_wallet_transactions_from_wallet_id'), 'wallet_transactions', ['from_wallet_id'], unique=True)
    op.create_index(op.f('ix_wallet_transactions_id'), 'wallet_transactions', ['id'], unique=True)
    op.create_index(op.f('ix_wallet_transactions_to_wallet_id'), 'wallet_transactions', ['to_wallet_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wallet_transactions_to_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_from_wallet_id'), table_name='wallet_transactions')
    op.drop_index(op.f('ix_wallet_transactions_bill_id'), table_name='wallet_transactions')
    op.drop_table('wallet_transactions')
    op.drop_index(op.f('ix_bills_task_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_submittedBy'), table_name='bills')
    op.drop_index(op.f('ix_bills_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_approved_by'), table_name='bills')
    op.drop_table('bills')
    # ### end Alembic commands ###
