"""rebuilt Wallets and Projects

Revision ID: f196ce399db9
Revises: d607ce1d3443
Create Date: 2026-05-31 00:25:10.517736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f196ce399db9'
down_revision: Union[str, Sequence[str], None] = 'd607ce1d3443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('wallet_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_foreign_key(None, 'projects', 'wallets', ['wallet_id'], ['id'])
    op.create_index(op.f('ix_wallets_id'), 'wallets', ['id'], unique=True)
    op.drop_constraint(op.f('wallets_project_id_fkey'), 'wallets', type_='foreignkey')
    op.drop_column('wallets', 'password_hash')
    op.drop_column('wallets', 'project_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wallets', sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('wallets', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('wallets_project_id_fkey'), 'wallets', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_wallets_id'), table_name='wallets')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_column('projects', 'wallet_id')
    # ### end Alembic commands ###
